import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
      <main className={styles.main}>
        <Head>
          <title>Renato Fekete</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.title}><h1>Coming soon!</h1></div>
      </main>
  
  )
}

export default Home
