import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
      <main className={styles.main}>
        <Head>
          <title>Renato Fekete</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.title}><h1>Hi, I'm Renato!</h1></div>
        <p>And this is my place where I'll store projects and where I'll play around with technology that I want to learn.</p>
        <p>This website is a constant work in progress, and I'll change it a lot.</p>
      </main>
  
  )
}

export default Home
